optimizer:
  params:
    weight_decay: 1.0211367763159735e-09
    lr: 1.921383137750599e-05
model:
  params:
    hidden_size: 1024
    objective_projection_mode: predictor_output
    ema_tau: 0.9999
    downstream_embedding_source: online
    context_position_mode: predictor
    predictor_hidden_multiplier: 1.0
    num_heads: 8
    query_aggregation: last
    dropout: 0.0
    num_blocks: 3
    num_passes_over_block: 2
    cat_emb_dim: 112
    num_emb_dim: 96
    embedding_size: 64
    masker:
      params:
        mask_prob: 0.7154913854446711
