optimizer:
  params:
    weight_decay: 0.0033490306814145526
    lr: 0.0021285784653066486
data:
  loaders:
    unsupervised_train:
      batch_size: 64
unsupervised_loss:
  params:
    temperature: 0.8641260928049379
training_model:
  head0:
    out_features: 385
model:
  encoder:
    params:
      num_layers: 3
      dropout: 9.474623680503043e-08
  preprocess:
    params:
      time_process: none
      num_norm: true
      cat_emb_dim: 19
      num_emb_dim: 23
  aggregation:
    name: TakeLastHidden
