optimizer:
  params:
    weight_decay: 5.825802756720572e-05
    lr: 0.00019186820010967337
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 72
      num_emb_dim: 64
      enc_hidden_size: 512
      emb_size: 1024
      enc_num_layers: 5
      n_head: 8
  aggregation:
    name: ValidHiddenMean
