optimizer:
  params:
    weight_decay: 8.795582994610583e-09
    lr: 2.523326667729402e-05
model:
  params:
    hidden_size: 544
    num_heads: 4
    query_aggregation: mean
    dropout: 0.15000000000000002
    num_blocks: 5
    num_passes_over_block: 1
    cat_emb_dim: 112
    num_emb_dim: 64
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.2837487915399288
        span_len: 56
        span_share: 0.65
        random_token_prob: 0.05
        keep_event_prob: 0.15
        partial_cat_feature_prob: 0.35000000000000003
        partial_num_feature_prob: 0.4
