optimizer:
  params:
    weight_decay: 5.448874630999136e-07
    lr: 0.00836371737021305
model:
  params:
    hidden_size: 128
    num_heads: 8
    dropout: 0.2
    num_blocks: 1
    num_passes_over_block: 2
    cat_emb_dim: 96
    num_emb_dim: 48
    masker:
      params:
        mask_prob: 0.20817772110880334
        span_len: 6
        span_share: 0.7000000000000001
        random_token_prob: 0.1
        keep_event_prob: 0.1
        partial_cat_feature_prob: 0.4
        partial_num_feature_prob: 0.25
