optimizer:
  params:
    weight_decay: 0.0053369751283846405
    lr: 0.0014824080962007853
model:
  params:
    hidden_size: 416
    num_heads: 1
    dropout: 0.15000000000000002
    num_blocks: 2
    num_passes_over_block: 1
    cat_emb_dim: 16
    num_emb_dim: 192
    masker:
      params:
        mask_prob: 0.11054169669807049
        span_len: 40
        span_share: 0.65
        random_token_prob: 0.15000000000000002
        keep_event_prob: 0.05
        partial_cat_feature_prob: 0.4
        partial_num_feature_prob: 0.2
