optimizer:
  params:
    weight_decay: 1.219891765424296e-07
    lr: 6.630217775360355e-05
model:
  params:
    hidden_size: 992
    num_heads: 4
    query_aggregation: mean
    dropout: 0.1
    num_blocks: 2
    num_passes_over_block: 2
    cat_emb_dim: 64
    num_emb_dim: 128
    embedding_size: 256
    masker:
      params:
        mask_prob: 0.7210513665453769
        span_len: 21
        span_share: 0.9
        random_token_prob: 0.15000000000000002
        keep_event_prob: 0.1
        partial_cat_feature_prob: 0.05
        partial_num_feature_prob: 0.25
