optimizer:
  params:
    weight_decay: 7.412080278491071e-06
    lr: 0.0005172968597435707
model:
  params:
    hidden_size: 416
    num_heads: 8
    dropout: 0.1
    num_blocks: 4
    num_passes_over_block: 2
    cat_emb_dim: 160
    num_emb_dim: 48
    masker:
      params:
        mask_prob: 0.10215363204819124
        span_len: 12
        span_share: 0.6
        random_token_prob: 0.05
        keep_event_prob: 0.0
        partial_cat_feature_prob: 0.2
        partial_num_feature_prob: 0.2
