data:
  preprocessing:
    gen_pipeline:
      max_seq_len: 1000000
  loaders:
    gen_train:
      batch_size: 1
    gen_train_val:
      batch_size: 1

test_data:
  preprocessing:
    gen_pipeline:
      max_seq_len: 1000000
  loaders:
    gen_test:
      batch_size: 1
