optimizer:
  params:
    weight_decay: 1.0539699274589132e-06
    lr: 0.0001444298424718306
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 24
      num_emb_dim: 128
      enc_hidden_size: 256
      emb_size: 256
      enc_num_layers: 2
      n_head: 4
  aggregation:
    name: ValidHiddenMean
