optimizer:
  params:
    weight_decay: 0.000689076770142218
    lr: 0.00027271309990286355
data:
  loaders:
    unsupervised_train:
      batch_size: 256
unsupervised_loss:
  params:
    temperature: 0.1894297066481915
training_model:
  head0:
    out_features: 499
model:
  encoder:
    params:
      num_layers: 3
      dropout: 0.09313541708092891
  preprocess:
    params:
      time_process: diff
      num_norm: false
      cat_emb_dim: 84
      num_emb_dim: 39
  aggregation:
    name: TakeLastHidden
