optimizer:
  params:
    weight_decay: 4.739318920417512e-05
    lr: 0.0008289678295788964
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 550
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 19
      num_emb_dim: 94
  aggregation:
    name: TakeLastHidden
