optimizer:
  params:
    weight_decay: 1.2385658332365924e-05
    lr: 0.0008560278257303339
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 932
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 5
      num_emb_dim: 75
  aggregation:
    name: TakeLastHidden
