optimizer:
  params:
    weight_decay: 1.222493826743282e-09
    lr: 6.971260570874938e-05
data:
  loaders:
    unsupervised_train:
      batch_size: 64
model:
  encoder:
    params:
      num_layers: 3
      dropout: 2.159851204154361e-09
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 62
      num_emb_dim: 28
  aggregation:
    name: TakeLastHidden
