optimizer:
  params:
    weight_decay: 2.5257889334441466e-05
    lr: 0.003663464435307374
unsupervised_loss:
  params:
    temperature: 0.015327925989335899
data:
  loaders:
    unsupervised_train:
      batch_size: 64
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 1004
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 109
      num_emb_dim: 90
  aggregation:
    name: TakeLastHidden
