optimizer:
  params:
    weight_decay: 1.0204038337816883e-05
    lr: 2.4386289542929573e-05
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 40
      num_emb_dim: 112
      enc_hidden_size: 1024
      emb_size: 1024
      enc_num_layers: 5
      n_head: 2
  aggregation:
    name: ValidHiddenMean
