optimizer:
  params:
    weight_decay: 8.341898541049732e-09
    lr: 0.0004651562452121479
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 128
      num_emb_dim: 48
      enc_hidden_size: 1024
      emb_size: 1024
      enc_num_layers: 3
      n_head: 2
  aggregation:
    name: TakeLastHidden
