optimizer:
  params:
    weight_decay: 5.782011240960713e-07
    lr: 0.0006045447140543974
model:
  params:
    hidden_size: 64
    num_heads: 1
    query_aggregation: last
    dropout: 0.05
    num_blocks: 3
    num_passes_over_block: 1
    cat_emb_dim: 80
    num_emb_dim: 48
    embedding_size: 256
    masker:
      params:
        mask_prob: 0.5807592186164822
        span_len: 91
        span_share: 0.2
        random_token_prob: 0.05
        keep_event_prob: 0.15
        partial_cat_feature_prob: 0.1
        partial_num_feature_prob: 0.05
