optimizer:
  params:
    weight_decay: 8.493134440795702e-07
    lr: 0.00020547246242597867
model:
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 80
      num_emb_dim: 8
      enc_hidden_size: 874
      emb_size: 1024
      enc_num_layers: 2
  aggregation:
    name: ValidHiddenMean
