optimizer:
  params:
    weight_decay: 1.126656782549769e-05
    lr: 7.275142963042729e-05
model:
  params:
    hidden_size: 640
    num_heads: 1
    query_aggregation: mean
    dropout: 0.05
    num_blocks: 2
    num_passes_over_block: 2
    cat_emb_dim: 112
    num_emb_dim: 112
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.6016475894571968
        span_len: 93
        span_share: 0.75
        random_token_prob: 0.2
        keep_event_prob: 0.15
        partial_cat_feature_prob: 0.35000000000000003
        partial_num_feature_prob: 0.0
