optimizer:
  params:
    weight_decay: 2.9998194182168894e-07
    lr: 2.972010702477362e-05
model:
  params:
    hidden_size: 576
    num_heads: 4
    query_aggregation: mean
    dropout: 0.3
    num_blocks: 2
    num_passes_over_block: 2
    cat_emb_dim: 64
    num_emb_dim: 32
    embedding_size: 256
    masker:
      params:
        mask_prob: 0.1658775008354504
        span_len: 62
        span_share: 0.35
        random_token_prob: 0.0
        keep_event_prob: 0.1
        partial_cat_feature_prob: 0.0
        partial_num_feature_prob: 0.25
