optimizer:
  params:
    weight_decay: 1.9973706782914543e-05
    lr: 6.448908185223686e-05
model:
  params:
    hidden_size: 736
    num_heads: 1
    query_aggregation: mean
    dropout: 0.0
    num_blocks: 1
    num_passes_over_block: 2
    cat_emb_dim: 48
    num_emb_dim: 96
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.6590013023435456
        span_len: 35
        span_share: 0.5
        random_token_prob: 0.15000000000000002
        keep_event_prob: 0.1
        partial_cat_feature_prob: 0.1
        partial_num_feature_prob: 0.15000000000000002
