optimizer:
  params:
    weight_decay: 8.510022576079817e-05
    lr: 0.00032205075636239394
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 88
      num_emb_dim: 56
      enc_hidden_size: 512
      emb_size: 1024
      enc_num_layers: 4
      n_head: 8
  aggregation:
    name: ValidHiddenMean
