data:
  preprocessing:
    contrastive_pipeline:
      batch_transforms:
        AUG_masking:
          AugmentationMasker:
            params:
              mask_prob: 0.25
              span_len: 39
              span_share: 0.65
              random_token_prob: 0.05
              keep_event_prob: 0.0
              partial_cat_feature_prob: 0.25
              partial_num_feature_prob: 0.0
