optimizer:
  params:
    weight_decay: 9.415939503211578e-06
    lr: 0.0004923071634668102
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 2
      hidden_size: 318
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 77
      num_emb_dim: 92
  aggregation:
    name: TakeLastHidden
