optimizer:
  params:
    weight_decay: 1.6355722955786759e-09
    lr: 0.0015761598739956364
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 969
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 76
      num_emb_dim: 23
  aggregation:
    name: TakeLastHidden
