optimizer:
  params:
    weight_decay: 0.00017827907169002386
    lr: 0.002984154473574416
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 8
      num_emb_dim: 72
      enc_hidden_size: 554
      emb_size: 256
      enc_num_layers: 1
  aggregation:
    name: TakeLastHidden
