optimizer:
  params:
    weight_decay: 1.3340205781450582e-10
    lr: 0.00015832270535637936
model:
  params:
    hidden_size: 640
    objective_projection_mode: predictor_output
    ema_tau: 0.9999
    downstream_embedding_source: online
    context_position_mode: encoder
    predictor_hidden_multiplier: 2.0
    num_heads: 8
    query_aggregation: mean
    dropout: 0.1
    num_blocks: 2
    num_passes_over_block: 1
    cat_emb_dim: 64
    num_emb_dim: 128
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.22827790320751834
