data_conf:
  dataset_name: "AGE"
  train_path: log/age/bert4rec/tests/age__bert4rec__regression__lgbm__trial22/seed_0/embeddings/train_postproc
  test_path: log/age/bert4rec/tests/age__bert4rec__regression__lgbm__trial22/seed_0/embeddings/test_postproc