data_conf:
  dataset_name: "TAOBAO"
  train_path: log/taobao/bert4rec/tests/random(2)/seed_0/embeddings/train_postproc
  test_path: log/taobao/bert4rec/tests/random(2)/seed_0/embeddings/test_postproc
  