optimizer:
  params:
    weight_decay: 3.4710627241159688e-09
    lr: 0.00010903696318239166
model:
  params:
    hidden_size: 896
    objective_projection_mode: online_target
    ema_tau: 0.9999
    downstream_embedding_source: target
    context_position_mode: predictor
    predictor_hidden_multiplier: 2.0
    num_heads: 1
    query_aggregation: last
    dropout: 0.0
    num_blocks: 2
    num_passes_over_block: 1
    cat_emb_dim: 80
    num_emb_dim: 64
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.6465374316941623
