optimizer:
  params:
    weight_decay: 3.364525129964992e-07
    lr: 3.2144853493937176e-05
data:
  loaders:
    unsupervised_train:
      batch_size: 64
model:
  encoder:
    params:
      num_layers: 2
      dropout: 5.2941682103569034e-09
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 48
      num_emb_dim: 43
  aggregation:
    name: TakeLastHidden
