optimizer:
  params:
    weight_decay: 1.2507292423271353e-08
    lr: 0.0010815262706746374
model:
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 112
      num_emb_dim: 104
      enc_hidden_size: 324
      emb_size: 1024
      enc_num_layers: 2
  aggregation:
    name: TakeLastHidden
