optimizer:
  params:
    weight_decay: 3.979663935705824e-07
    lr: 0.0011694696999869313
unsupervised_loss:
  params:
    temperature: 75.57209182877862
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 890
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 43
      num_emb_dim: 119
  aggregation:
    name: TakeLastHidden
