optimizer:
  params:
    weight_decay: 2.5692043349401723e-09
    lr: 0.0005001931287484384
model:
  params:
    hidden_size: 1024
    num_heads: 2
    query_aggregation: mean
    dropout: 0.0
    num_blocks: 1
    num_passes_over_block: 2
    cat_emb_dim: 48
    num_emb_dim: 96
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.6171832560131852
        span_len: 83
        span_share: 0.2
        random_token_prob: 0.05
        keep_event_prob: 0.15
        partial_cat_feature_prob: 0.15000000000000002
        partial_num_feature_prob: 0.05
