optimizer:
  params:
    weight_decay: 1.8871501620442023e-09
    lr: 0.0010911462767245303
model:
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 72
      num_emb_dim: 40
      enc_hidden_size: 512
      emb_size: 1024
      enc_num_layers: 4
      n_head: 4
  aggregation:
    name: ValidHiddenMean
