optimizer:
  params:
    weight_decay: 2.420728468046804e-07
    lr: 1.460814997293647e-05
unsupervised_loss:
  params:
    temperature: 0.028548762607764386
data:
  loaders:
    unsupervised_train:
      batch_size: 8
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 971
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 114
      num_emb_dim: 43
  aggregation:
    name: TakeLastHidden
