optimizer:
  params:
    weight_decay: 9.889217921490572e-06
    lr: 7.227684236838754e-05
unsupervised_loss:
  params:
    temperature: 15.558193345390064
data:
  loaders:
    unsupervised_train:
      batch_size: 4
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 898
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 89
      num_emb_dim: 26
  aggregation:
    name: ValidHiddenMean
