optimizer:
  params:
    weight_decay: 9.062810887656091e-10
    lr: 4.336446461712777e-05
unsupervised_loss:
  params:
    temperature: 0.10637024271541673
data:
  loaders:
    unsupervised_train:
      batch_size: 256
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 104
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 10
      num_emb_dim: 39
  aggregation:
    name: TakeLastHidden
