optimizer:
  params:
    weight_decay: 2.088009960288448e-10
    lr: 7.021908653228537e-05
unsupervised_loss:
  params:
    temperature: 0.12435257706865638
data:
  loaders:
    unsupervised_train:
      batch_size: 512
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 937
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 106
      num_emb_dim: 78
  aggregation:
    name: ValidHiddenMean
