optimizer:
  params:
    weight_decay: 0.0041887217082431155
    lr: 0.00012394877666794445
model:
  encoder:
    params:
      num_layers: 2
      dropout: 1.4738774749002656e-06
  preprocess:
    params:
      time_process: none
      num_norm: true
      cat_emb_dim: 53
      num_emb_dim: 38
  aggregation:
    name: TakeLastHidden
unsupervised_loss:
  params:
    margin: 0.20510161992037748
