optimizer:
  params:
    weight_decay: 1.9943265256221078e-07
    lr: 2.7076764045682346e-05
model:
  params:
    hidden_size: 640
    objective_projection_mode: predictor_output
    ema_tau: 0.99
    downstream_embedding_source: online
    context_position_mode: predictor
    predictor_hidden_multiplier: 2.0
    num_heads: 4
    query_aggregation: last
    dropout: 0.15000000000000002
    num_blocks: 4
    num_passes_over_block: 2
    cat_emb_dim: 64
    num_emb_dim: 96
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.46833533271712047
