optimizer:
  params:
    weight_decay: 0.00022938627985587663
    lr: 1.1401790273637967e-05
model:
  params:
    hidden_size: 288
    num_heads: 1
    query_aggregation: mean
    dropout: 0.1
    num_blocks: 5
    num_passes_over_block: 1
    cat_emb_dim: 64
    num_emb_dim: 48
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.41943074868617913
        span_len: 48
        span_share: 0.4
        random_token_prob: 0.05
        keep_event_prob: 0.15
        partial_cat_feature_prob: 0.0
        partial_num_feature_prob: 0.35000000000000003
