data:
  preprocessing:
    contrastive_pipeline:
      batch_transforms:
        AUG_masking:
          AugmentationMasker:
            params:
              mask_prob: 0.4
              span_len: 12
              span_share: 0.7
              random_token_prob: 0.05
              keep_event_prob: 0.1
              partial_cat_feature_prob: 0.05
              partial_num_feature_prob: 0.25
