optimizer:
  params:
    weight_decay: 3.87643842713274e-05
    lr: 0.002006991729687233
data:
  loaders:
    unsupervised_train:
      batch_size: 64
model:
  encoder:
    params:
      num_layers: 5
      hidden_size: 67
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 103
      num_emb_dim: 91
  aggregation:
    name: TakeLastHidden
