optimizer:
  params:
    weight_decay: 1.8290224075023442e-07
    lr: 1.3855790352571711e-05
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 40
      num_emb_dim: 24
      enc_hidden_size: 256
      emb_size: 1024
      enc_num_layers: 1
      n_head: 4
  aggregation:
    name: TakeLastHidden
