optimizer:
  params:
    weight_decay: 5.173759909120325e-10
    lr: 6.254350959574795e-05
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 56
      num_emb_dim: 104
      enc_hidden_size: 64
      emb_size: 1024
      enc_num_layers: 5
      n_head: 8
  aggregation:
    name: ValidHiddenMean
