optimizer:
  params:
    weight_decay: 1.139842855280318e-08
    lr: 8.330810652375205e-05
unsupervised_loss:
  params:
    temperature: 5.447831409875852
data:
  loaders:
    unsupervised_train:
      batch_size: 64
model:
  encoder:
    params:
      num_layers: 3
      hidden_size: 210
  preprocess:
    params:
      time_process: diff
      num_norm: false
      cat_emb_dim: 85
      num_emb_dim: 83
  aggregation:
    name: ValidHiddenMean
