optimizer:
  params:
    weight_decay: 2.8501602007815025e-09
    lr: 2.850387211498416e-05
unsupervised_loss:
  params:
    temperature: 9.212928640044879
data:
  loaders:
    unsupervised_train:
      batch_size: 512
model:
  encoder:
    params:
      num_layers: 3
      hidden_size: 424
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 109
      num_emb_dim: 99
  aggregation:
    name: ValidHiddenMean
