optimizer:
  params:
    weight_decay: 2.4572565995149947e-06
    lr: 0.004509053301995342
data:
  loaders:
    unsupervised_train:
      batch_size: 256
model:
  encoder:
    params:
      num_layers: 2
      hidden_size: 177
  emb_head:
    params:
      out_features: 1024
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 34
      num_emb_dim: 23
  aggregation:
    name: TakeLastHidden
