optimizer:
  params:
    weight_decay: 0.003930691750402924
    lr: 1.4264685437964448e-05
data:
  loaders:
    unsupervised_train:
      batch_size: 256
model:
  encoder:
    params:
      num_layers: 4
      hidden_size: 105
  emb_head:
    params:
      out_features: 1024
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 115
      num_emb_dim: 38
  aggregation:
    name: TakeLastHidden
