optimizer:
  params:
    weight_decay: 0.000797134701759211
    lr: 0.009407659862009
data:
  loaders:
    unsupervised_train:
      batch_size: 256
model:
  encoder:
    params:
      num_layers: 2
      hidden_size: 237
  emb_head:
    params:
      out_features: 1024
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 4
      num_emb_dim: 43
  aggregation:
    name: TakeLastHidden
