data:
  loaders:
    unsupervised_train:
      batch_size: 64

optimizer:
  params:
    weight_decay: 1.e-10  # original: 0.0
    lr: 0.001
model:
  encoder:
    params:
      hidden_size: 800
      num_layers: 1
      dropout: 1.e-10  # original: no dropout
  preprocess:
    params:
      time_process: cat # cat_periodic
      # n_periodic: 4
      num_norm: true
      # emb_noise: 0.003
      cat_emb_dim: 16
      num_emb_dim: 16
  aggregation:
    name: TakeLastHidden
unsupervised_loss:
  params:
    margin: 0.5
unsupervised_trainer:
  total_iters: 100000
