optimizer:
  params:
    weight_decay: 1.1467952484541963e-10
    lr: 0.00011798276216746506
model:
  params:
    hidden_size: 896
    objective_projection_mode: predictor_output
    ema_tau: 0.9999
    downstream_embedding_source: online
    context_position_mode: predictor
    predictor_hidden_multiplier: 0.5
    num_heads: 1
    query_aggregation: mean
    dropout: 0.0
    num_blocks: 1
    num_passes_over_block: 1
    cat_emb_dim: 80
    num_emb_dim: 64
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.2550854329129165
