optimizer:
  params:
    weight_decay: 4.889658295718471e-09
    lr: 0.0007544834224263946
model:
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 96
      num_emb_dim: 16
      enc_hidden_size: 768
      emb_size: 64
      enc_num_layers: 1
      n_head: 2
  aggregation:
    name: TakeLastHidden
