optimizer:
  params:
    weight_decay: 7.846463426165272e-07
    lr: 0.0029965004157103503
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 64
      num_emb_dim: 128
      enc_hidden_size: 1024
      emb_size: 256
      enc_num_layers: 1
      n_head: 8
  aggregation:
    name: ValidHiddenMean
