optimizer:
  params:
    weight_decay: 0.0003828112484146361
    lr: 0.001715456331096665
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 104
      num_emb_dim: 64
      enc_hidden_size: 768
      emb_size: 1024
      enc_num_layers: 5
      n_head: 8
  aggregation:
    name: TakeLastHidden
