optimizer:
  params:
    weight_decay: 1.8694914721832027e-06
    lr: 0.002761914318018509
model:
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 96
      num_emb_dim: 40
      enc_hidden_size: 256
      emb_size: 1024
      enc_num_layers: 5
      n_head: 1
  aggregation:
    name: TakeLastHidden
