optimizer:
  params:
    weight_decay: 1.8262947532428293e-08
    lr: 0.00048655995433994134
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 40
      num_emb_dim: 96
      enc_hidden_size: 626
      emb_size: 1024
      enc_num_layers: 1
  aggregation:
    name: ValidHiddenMean
