optimizer:
  params:
    weight_decay: 1.8291466088479693e-08
    lr: 0.0016006595934872486
data:
  loaders:
    unsupervised_train:
      batch_size: 64
model:
  encoder:
    params:
      num_layers: 3
      dropout: 0.004507814028612756
  preprocess:
    params:
      time_process: diff
      num_norm: false
      cat_emb_dim: 92
      num_emb_dim: 127
  aggregation:
    name: TakeLastHidden
