optimizer:
  params:
    weight_decay: 2.8899604415690226e-05
    lr: 9.59935409324668e-05
unsupervised_loss:
  params:
    temperature: 5.369867664410337
data:
  loaders:
    unsupervised_train:
      batch_size: 64
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 381
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 7
      num_emb_dim: 120
  aggregation:
    name: TakeLastHidden
