optimizer:
  params:
    weight_decay: 1.6123914067151055e-07
    lr: 0.0004556272923341389
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 16
      num_emb_dim: 104
      enc_hidden_size: 351
      emb_size: 1024
      enc_num_layers: 1
  aggregation:
    name: TakeLastHidden
