optimizer:
  params:
    weight_decay: 0.00013419152926640913
    lr: 0.0023431617320159213
model:
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 104
      num_emb_dim: 24
      enc_hidden_size: 768
      emb_size: 1024
      enc_num_layers: 5
      n_head: 8
  aggregation:
    name: TakeLastHidden
