optimizer:
  params:
    weight_decay: 1.4145300414156241e-09
    lr: 2.4954956979376157e-05
model:
  params:
    hidden_size: 544
    num_heads: 8
    query_aggregation: last
    dropout: 0.25
    num_blocks: 2
    num_passes_over_block: 1
    cat_emb_dim: 64
    num_emb_dim: 96
    embedding_size: 256
    masker:
      params:
        mask_prob: 0.13758242704844306
        span_len: 15
        span_share: 0.35
        random_token_prob: 0.05
        keep_event_prob: 0.15
        partial_cat_feature_prob: 0.30000000000000004
        partial_num_feature_prob: 0.15000000000000002
