optimizer:
  params:
    weight_decay: 1.411116384358975e-07
    lr: 0.0004125949296217017
model:
  params:
    hidden_size: 576
    num_heads: 4
    query_aggregation: last
    dropout: 0.3
    num_blocks: 3
    num_passes_over_block: 1
    cat_emb_dim: 32
    num_emb_dim: 32
    embedding_size: 256
    masker:
      params:
        mask_prob: 0.6760409197069757
        span_len: 33
        span_share: 0.45000000000000007
        random_token_prob: 0.05
        keep_event_prob: 0.0
        partial_cat_feature_prob: 0.4
        partial_num_feature_prob: 0.35000000000000003
