optimizer:
  params:
    weight_decay: 2.0071972398900897e-10
    lr: 0.0010733641443340957
model:
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 80
      num_emb_dim: 112
      enc_hidden_size: 164
      emb_size: 1024
      enc_num_layers: 5
  aggregation:
    name: TakeLastHidden
