optimizer:
  params:
    weight_decay: 2.6278477424191954e-10
    lr: 0.0003260970742487198
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 780
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 74
      num_emb_dim: 63
  aggregation:
    name: ValidHiddenMean
