optimizer:
  params:
    weight_decay: 9.445306093779693e-07
    lr: 0.00018230321831688275
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 3
      dropout: 3.0409084217046393e-09
  preprocess:
    params:
      time_process: diff
      num_norm: false
      cat_emb_dim: 69
      num_emb_dim: 72
  aggregation:
    name: TakeLastHidden
