optimizer:
  params:
    weight_decay: 2.1508539611141067e-07
    lr: 0.00022770726282231226
data:
  loaders:
    unsupervised_train:
      batch_size: 16
model:
  encoder:
    params:
      num_layers: 3
      hidden_size: 237
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 127
      num_emb_dim: 10
  aggregation:
    name: TakeLastHidden
