optimizer:
  params:
    weight_decay: 2.324153892007928e-05
    lr: 5.117654307915563e-05
model:
  encoder:
    params:
      num_layers: 1
      dropout: 6.183746594107366e-07
  preprocess:
    params:
      time_process: diff
      num_norm: false
      cat_emb_dim: 26
      num_emb_dim: 54
  aggregation:
    name: ValidHiddenMean
unsupervised_loss:
  params:
    margin: 0.2038922059615269
unsupervised_trainer:
  total_iters: 100000
