optimizer:
  params:
    weight_decay: 1.0457658130018826e-09
    lr: 0.000184621027213796
unsupervised_loss:
  params:
    temperature: 0.3699021230735154
data:
  loaders:
    unsupervised_train:
      batch_size: 256
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 499
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 52
      num_emb_dim: 53
  aggregation:
    name: TakeLastHidden
