optimizer:
  params:
    weight_decay: 2.5807238137010862e-08
    lr: 0.008779794000726445
unsupervised_loss:
  params:
    temperature: 0.020379895424894674
data:
  loaders:
    unsupervised_train:
      batch_size: 64
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 468
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 38
      num_emb_dim: 81
  aggregation:
    name: ValidHiddenMean
