optimizer:
  params:
    weight_decay: 1.596914313125766e-08
    lr: 0.0013343935262604084
model:
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 104
      num_emb_dim: 96
      enc_hidden_size: 225
      emb_size: 1024
      enc_num_layers: 2
  aggregation:
    name: ValidHiddenMean
