optimizer:
  params:
    weight_decay: 5.0248783275064635e-08
    lr: 0.0018136954034113496
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 262
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 74
      num_emb_dim: 124
  aggregation:
    name: TakeLastHidden
