optimizer:
  params:
    weight_decay: 1.789608161440001e-06
    lr: 0.0005374158084584988
data:
  loaders:
    unsupervised_train:
      batch_size: 512
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 490
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 1
      num_emb_dim: 87
  aggregation:
    name: TakeLastHidden
