optimizer:
  params:
    weight_decay: 1.4186563013139115e-10
    lr: 0.00012301820445680912
model:
  params:
    hidden_size: 384
    objective_projection_mode: online_target
    ema_tau: 0.9999
    downstream_embedding_source: online
    context_position_mode: encoder
    predictor_hidden_multiplier: 2.0
    num_heads: 8
    query_aggregation: mean
    dropout: 0.05
    num_blocks: 1
    num_passes_over_block: 1
    cat_emb_dim: 32
    num_emb_dim: 80
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.2861646546765834
