log_dir: log/full/electric_devices
patience: 10
n_classes: 7
main_metric: MulticlassAccuracy
main_loss: 
  name: nn.CrossEntropyLoss
tasks:
- target__forecast__local__r2
- target__clf__global__accuracy+f1_macro

ee:
cc: 
nn:
  - sequence

data:
  dataset:
    parquet_path: "data/electric_devices/preprocessed_full/train"
    random_split: true
    split_seed: 42

    split_sizes: 
      - 0.85   # train
      - 0.15  # train_val

  preprocessing:
    common_pipeline: &common_pipeline
      max_seq_len: 96
      time_name: time
      index_name: sequence_id
      target_name: _seq_len
      cat_cardinalities: ${cc}
      num_names: ${nn}
      batch_transforms:
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - TargetToLong
        - MaskValid
    gen_pipeline:
      <<: *common_pipeline
      max_seq_len: 10000
    contrastive_pipeline:
      <<: *common_pipeline
      batch_transforms:
        TTF:
          TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        TTL:
          TargetToLong
        MV:
          MaskValid
        CT:
          ContrastiveTarget
        AUG_slices:
          RandomSlices:
            split_count: 5
            cnt_min: 25
            cnt_max: 200
            short_seq_crop_rate: 0.8
    primenet_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - TargetToLong
        - MaskValid
        - PrimeNetSampler:
            segment_num: 3

  loaders:
    train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      drop_incomplete: true
      shuffle: true
      loop: false
      num_workers: 4
      random_seed: 42
    full_train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    train_val:
      split_idx: 1
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    gen_train:
      split_idx: 0
      preprocessing: gen_pipeline
      batch_size: 16
      num_workers: 4
    gen_train_val:
      split_idx: 1
      preprocessing: gen_pipeline
      batch_size: 16
      num_workers: 4


test_data:
  dataset:
    parquet_path: "data/electric_devices/preprocessed_full/test"
    split_sizes: 
      - 1.0
  preprocessing:
    common_pipeline: *common_pipeline
    gen_pipeline:
      <<: *common_pipeline
      max_seq_len: 10000
  loaders:
    test:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    gen_test:
      split_idx: 0
      preprocessing: gen_pipeline
      batch_size: 16
      num_workers: 4

metrics:
  - name: ${main_metric}
    params: 
      num_classes: ${n_classes}
