log_dir: log/full/taobao
patience: 10
n_classes: 4
main_metric: MulticlassAUROC
main_loss: 
  name: nn.CrossEntropyLoss
tasks:
- target__clf__local__accuracy+f1_macro
- target__anomaly__global__roc_auc
- target__reg__local__r2
- target__forecast__local__r2

cc: 
  behavior_type: 5
  item_category: 8917
ee:
nn:

data:
  dataset:
    parquet_path: "data/taobao/preprocessed_full/train"
    random_split: true
    split_seed: 42

    split_sizes: 
      - 0.85   # train
      - 0.15  # train_val

  preprocessing:
    common_pipeline: &common_pipeline
      max_seq_len: 1000
      time_name: time
      index_name: client_id
      target_name: _seq_len
      cat_cardinalities: ${cc}
      batch_transforms:
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - MaskValid
    gen_pipeline:
      <<: *common_pipeline
      max_seq_len: 1000000
    contrastive_pipeline:
      <<: *common_pipeline
      batch_transforms:
        TTF:
          TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        MV:
          MaskValid
        CT:
          ContrastiveTarget
        AUG_slices:
          RandomSlices:
            split_count: ${oc.select:additional_params.split_count, 5}
            cnt_min: 64
            cnt_max: 192
            short_seq_crop_rate: 0.8
            seed: 0
        AUG_masking:
          AugmentationMasker:
            name: MixedMasker
            number_of_instances: 3
            add_initial: True
            params:
              cat_cardinalities: ${cc}
              mask_prob: 0.2
              span_len: 10
              span_share: 0.5
              random_token_prob: 0.1  # How many masked tokens going to be corrupted not masked
              keep_event_prob: 0.0  # Keep selected events unchanged for both cat and num
              num_mask_fill: zero
              partial_cat_feature_prob: 0.0
              partial_num_feature_prob: 0.0
    primenet_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - MaskValid
        - PrimeNetSampler:
            segment_num: 3

  loaders:
    train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      drop_incomplete: true
      shuffle: true
      loop: false
      num_workers: 4
      random_seed: 42
    full_train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    train_val:
      split_idx: 1
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    gen_train:
      split_idx: 0
      preprocessing: gen_pipeline
      batch_size: 32
      num_workers: 4
    gen_train_val:
      split_idx: 1
      preprocessing: gen_pipeline
      batch_size: 32
      num_workers: 4

test_data:
  dataset:
    parquet_path: "data/taobao/preprocessed_full/test"
    split_sizes: 
      - 1.0
  preprocessing:
    common_pipeline: *common_pipeline
    gen_pipeline:
      <<: *common_pipeline
      max_seq_len: 1000000
  loaders:
    test:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    gen_test:
      split_idx: 0
      preprocessing: gen_pipeline
      batch_size: 32
      num_workers: 4

metrics:
  - name: ${main_metric}
    params: 
      num_classes: ${n_classes}
