log_dir: log/full/twitter
patience: 10
n_classes: 3
main_metric: MulticlassAUROC
main_loss:
  name: nn.CrossEntropyLoss
tasks:
- target__clf__global__accuracy+f1_macro
- target__reg_mentions__global__r2
- target__anomaly__global__roc_auc

ee:
cc: 
  char: 190
nn:

data:
  dataset:
    parquet_path: "data/twitter/preprocessed_full/train"
    random_split: true
    split_seed: 42
    split_sizes: 
      - 0.85   # train
      - 0.15  # train_val

  preprocessing:
    common_pipeline: &common_pipeline
      max_seq_len: 512
      time_name: char_number
      index_name: tweet_id
      target_name: _seq_len
      cat_cardinalities: ${cc}
      num_names: ${nn}
      batch_transforms:
        TTF:
          TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        MV:
          MaskValid
    gen_pipeline:
      <<: *common_pipeline
      max_seq_len: 10000
    contrastive_pipeline:
      <<: *common_pipeline
      batch_transforms:
        TTF:
          TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        MV:
          MaskValid
        CT:
          ContrastiveTarget
        AUG_slices:
          RandomSlices:
            split_count: ${oc.select:additional_params.split_count, 5}
            cnt_min: 25
            cnt_max: 100
            short_seq_crop_rate: 0.8
            seed: 0

        AUG_masking:
          AugmentationMasker:
            name: MixedMasker
            number_of_instances: 3
            add_initial: True
            params:
              cat_cardinalities: ${cc}
              mask_prob: 0.35
              span_len: 40
              span_share: 0.55
              random_token_prob: 0.05
              keep_event_prob: 0.1
              num_mask_fill: zero
              partial_cat_feature_prob: 0.1
              partial_num_feature_prob: 0.0
  loaders:
    train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      drop_incomplete: true
      shuffle: true
      loop: false
      num_workers: 4
      random_seed: 42
    full_train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    train_val:
      split_idx: 1
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    gen_train:
      split_idx: 0
      preprocessing: gen_pipeline
      batch_size: 16
      num_workers: 4
    gen_train_val:
      split_idx: 1
      preprocessing: gen_pipeline
      batch_size: 16
      num_workers: 4

test_data:
  dataset:
    parquet_path: "data/twitter/preprocessed_full/test"
    split_sizes: 
      - 1.0
  preprocessing:
    common_pipeline: *common_pipeline
    gen_pipeline:
      <<: *common_pipeline
      max_seq_len: 10000
  loaders:
    test:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    gen_test:
      split_idx: 0
      preprocessing: gen_pipeline
      batch_size: 16
      num_workers: 4

metrics:
  - name: ${main_metric}
    params: 
      num_classes: ${n_classes}
