optimizer:
  params:
    weight_decay: 7.382926076642427e-05
    lr: 0.0021942937417467213
data:
  loaders:
    unsupervised_train:
      batch_size: 64
unsupervised_loss:
  params:
    temperature: 0.2052796746426425
training_model:
  head0:
    out_features: 229
model:
  encoder:
    params:
      num_layers: 2
      dropout: 0.00023370804979918965
  preprocess:
    params:
      time_process: none
      num_norm: false
      cat_emb_dim: 105
      num_emb_dim: 107
  aggregation:
    name: ValidHiddenMean
