optimizer:
  params:
    weight_decay: 1.9010869265296083e-09
    lr: 0.0003591745970829671
unsupervised_loss:
  params:
    temperature: 19.77402223384952
data:
  loaders:
    unsupervised_train:
      batch_size: 64
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 612
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 29
      num_emb_dim: 110
  aggregation:
    name: TakeLastHidden
