optimizer:
  params:
    weight_decay: 3.899285722483746e-08
    lr: 1.1744085651407951e-05
unsupervised_loss:
  params:
    temperature: 0.015834428468555723
data:
  loaders:
    unsupervised_train:
      batch_size: 256
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 926
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 85
      num_emb_dim: 121
  aggregation:
    name: TakeLastHidden
