optimizer:
  params:
    weight_decay: 0.00444801114207267
    lr: 0.0008703345069310275
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 88
      num_emb_dim: 96
      enc_hidden_size: 296
      emb_size: 256
      enc_num_layers: 2
  aggregation:
    name: ValidHiddenMean
