optimizer:
  params:
    weight_decay: 5.9279746167183955e-05
    lr: 0.0001286836866510268
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 920
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 112
      num_emb_dim: 84
  aggregation:
    name: TakeLastHidden
