optimizer:
  params:
    weight_decay: 2.679781038527905e-09
    lr: 1.6452916375822122e-05
model:
  params:
    hidden_size: 704
    num_heads: 8
    query_aggregation: last
    dropout: 0.0
    num_blocks: 2
    num_passes_over_block: 2
    cat_emb_dim: 64
    num_emb_dim: 112
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.6983305173355149
        span_len: 76
        span_share: 0.30000000000000004
        random_token_prob: 0.05
        keep_event_prob: 0.15
        partial_cat_feature_prob: 0.30000000000000004
        partial_num_feature_prob: 0.05
