optimizer:
  params:
    weight_decay: 3.3307612352355097e-08
    lr: 0.0004978877046232543
model:
  params:
    hidden_size: 256
    objective_projection_mode: online_target
    ema_tau: 0.9999
    downstream_embedding_source: online
    context_position_mode: both
    predictor_hidden_multiplier: 2.0
    num_heads: 2
    query_aggregation: last
    dropout: 0.15000000000000002
    num_blocks: 1
    num_passes_over_block: 2
    cat_emb_dim: 32
    num_emb_dim: 80
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.6928535451495955
