optimizer:
  params:
    weight_decay: 2.6688257615834915e-10
    lr: 3.273159775822882e-05
model:
  params:
    hidden_size: 768
    objective_projection_mode: predictor_output
    ema_tau: 0.999
    downstream_embedding_source: online
    context_position_mode: predictor
    predictor_hidden_multiplier: 0.5
    num_heads: 2
    query_aggregation: last
    dropout: 0.05
    num_blocks: 1
    num_passes_over_block: 2
    cat_emb_dim: 48
    num_emb_dim: 48
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.5929978326522372
