optimizer:
  params:
    weight_decay: 1.8645890756281058e-06
    lr: 0.0006167215221785066
data:
  loaders:
    unsupervised_train:
      batch_size: 512
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 396
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 15
      num_emb_dim: 76
  aggregation:
    name: TakeLastHidden
