optimizer:
  params:
    weight_decay: 5.781478630175239e-05
    lr: 1.3419974315624331e-05
data:
  loaders:
    unsupervised_train:
      batch_size: 4
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 802
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 45
      num_emb_dim: 30
  aggregation:
    name: TakeLastHidden
