optimizer:
  params:
    weight_decay: 7.628661069694559e-07
    lr: 0.002698597593722281
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 72
      num_emb_dim: 96
      enc_hidden_size: 256
      emb_size: 64
      enc_num_layers: 5
      n_head: 4
  aggregation:
    name: TakeLastHidden
