optimizer:
  params:
    weight_decay: 7.169373342503604e-08
    lr: 5.554746043078263e-05
unsupervised_loss:
  params:
    temperature: 6.414750689507627
data:
  loaders:
    unsupervised_train:
      batch_size: 16
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 682
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 58
      num_emb_dim: 125
  aggregation:
    name: TakeLastHidden
