optimizer:
  params:
    weight_decay: 1.0e-08
    lr: 0.001
unsupervised_loss:
  params:
    temperature: 1
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 512
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 64
      num_emb_dim: 64
  aggregation:
    name: TakeLastHidden
