optimizer:
  params:
    weight_decay: 7.493267716294813e-08
    lr: 4.595764482062135e-05
model:
  params:
    hidden_size: 1024
    objective_projection_mode: predictor_output
    ema_tau: 0.9999
    downstream_embedding_source: online
    context_position_mode: both
    predictor_hidden_multiplier: 1.0
    num_heads: 4
    query_aggregation: last
    dropout: 0.05
    num_blocks: 1
    num_passes_over_block: 2
    cat_emb_dim: 80
    num_emb_dim: 128
    embedding_size: 64
    masker:
      params:
        mask_prob: 0.27555434086814024
