optimizer:
  params:
    weight_decay: 5.662433965773244e-07
    lr: 0.0014555830498146243
unsupervised_loss:
  params:
    temperature: 0.13773863012359497
data:
  loaders:
    unsupervised_train:
      batch_size: 256
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 896
  preprocess:
    params:
      time_process: diff
      num_norm: false
      cat_emb_dim: 120
      num_emb_dim: 120
  aggregation:
    name: ValidHiddenMean
