optimizer:
  params:
    weight_decay: 5.828606369212457e-07
    lr: 0.0014680425674202108
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 375
  preprocess:
    params:
      time_process: diff
      num_norm: false
      cat_emb_dim: 77
      num_emb_dim: 121
  aggregation:
    name: ValidHiddenMean
