optimizer:
  params:
    weight_decay: 3.2868270913006895e-08
    lr: 1.9724249191178898e-05
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 88
      num_emb_dim: 16
      enc_hidden_size: 231
      emb_size: 64
      enc_num_layers: 5
  aggregation:
    name: TakeLastHidden
