optimizer:
  params:
    weight_decay: 7.431841539727404e-09
    lr: 3.5046209851482236e-05
model:
  params:
    hidden_size: 288
    num_heads: 4
    dropout: 0.05
    num_blocks: 1
    num_passes_over_block: 1
    cat_emb_dim: 160
    num_emb_dim: 128
    masker:
      params:
        mask_prob: 0.1002941505669456
        span_len: 27
        span_share: 0.15000000000000002
        random_token_prob: 0.1
        keep_event_prob: 0.1
        partial_cat_feature_prob: 0.1
        partial_num_feature_prob: 0.25
