method_name: bert4rec_short
runner_name: BertRunner

main_loss:
  name: ModelLoss
  params: {}

metrics: null

trainer:
  ckpt_track_metric: loss
  metrics_on_train: false
  patience: ${patience}
  total_iters: 100_000
  # ckpt_resume: ''
model:
  name: Bert4Rec
  params:
    cat_cardinalities: ${cc}
    num_features: ${nn}
    time_process: ${model.preprocess.params.time_process}
    cat_emb_dim: 64
    num_emb_dim: 64
    num_norm: false
    reconstruction_ce_weight: 1.0
    reconstruction_mse_weight: 1.0
    ignore_index: -100
    masker:
      name: MixedMasker
      params:
        mask_prob: 0.2
        span_len: 10
        span_share: 0.5
        random_token_prob: 0.1  # How many masked tokens going to be corrupted not masked
        keep_event_prob: 0.0  # Keep selected events unchanged for both cat and num
        num_mask_fill: zero
        partial_cat_feature_prob: 0.1
        partial_num_feature_prob: 0.1
    query_aggregation: last
    max_len: ${data.preprocessing.common_pipeline.max_seq_len}
    hidden_size: 128
    embedding_size: 128
    num_blocks: 4
    num_heads: 4
    num_passes_over_block: 1
    dropout: 0.05
    enable_positional_embedding: true
  preprocess:
    params:
      time_process: "cat"


optimizer:
  name: Adam
  params:
    lr: 1.e-3
    weight_decay: 1.e-6


optuna:
  params:
    n_trials: 100
    n_startup_trials: 10
    target_metric: ${tasks}
  suggestions:
    optimizer.params.lr: [suggest_float, {low: 1.e-5, high: 1.e-2, log: True}]
    model.params.hidden_size: [suggest_int, {low: 64, high: 1024, step: 32}]
    model.params.query_aggregation: [suggest_categorical, {choices: [last, mean]}]
    model.params.embedding_size: [suggest_categorical, {choices: [64, 256, 1024]}]

    model.params.masker.params.mask_prob: [suggest_float, {low: 0.1, high: 0.8, log: False}]
    model.params.masker.params.span_len: [suggest_int, {low: 5, high: 100, log: False}]
    model.params.masker.params.span_share: [suggest_float, {low: 0.1, high: 0.9, step: 0.05}]
    model.params.masker.params.partial_cat_feature_prob: [suggest_float, {low: 0., high: 0.5, step: 0.05}]
    model.params.masker.params.partial_num_feature_prob: [suggest_float, {low: 0., high: 0.5, step: 0.05}]
    # model.params.masker.params.num_mask_fill: [suggest_categorical, {choices: [zero, mean, noise]}]
    # taobao + zvuk