method_name: coles
runner_name: UnsupervisedEmbedRunner    

data:
  preprocessing:
    contrastive_pipeline:
      batch_transforms:
        AUG_slices:
          RandomSlices:
            split_count: 5
        AUG_masking:
  loaders:
    unsupervised_train:
      split_idx: 0
      preprocessing: contrastive_pipeline
      batch_size: 128
      drop_incomplete: true
      shuffle: true
      num_workers: 4
      labeled: False
    unsupervised_train_val:
      split_idx: 1
      preprocessing: contrastive_pipeline
      batch_size: ${data.loaders.unsupervised_train.batch_size}
      num_workers: 4
      labeled: False


unsupervised_loss:
  name: ContrastiveLoss
  params: 
    selector: HardNegativePairSelector
    neg_count: 5
    margin: 1
unsupervised_metrics: null
unsupervised_trainer:
  ckpt_track_metric: epoch
  metrics_on_train: true
  patience: -1
  total_iters: 100_000

training_model:
  preprocess: ${model.preprocess}
  encoder: ${model.encoder}
  aggregation: ${model.aggregation}
  head_1:
    name: nn.Linear
    params:
      in_features: output_dim_from_prev
      out_features: 64
  relu:
    name: nn.ReLU
  head_2:
    name: nn.Linear
    params:
      in_features: 64
      out_features: 64


model:
  preprocess:
    name: Batch2Seq
    params:
      cat_cardinalities: ${cc}
      num_features: ${nn}
      emb_dimensionalities: ${ee}
      cat_emb_dim: 64
      num_emb_dim: 64
      time_process: "cat" # "diff" | "cat" | "cat_periodic" | "none"
      num_norm: false
  encoder: 
    name: GRU
    params:
      input_size: output_dim_from_prev
      hidden_size: 512
      num_layers: 1
  aggregation:
    name: TakeLastHidden

optimizer:
  name: Adam
  params:
    lr: 1.e-3
    weight_decay: 1.e-8

#lr_scheduler:
#  name: StepLR
#  params:
#    step_size: 30
#    gamma: 0.9025

optuna:
  params:
    n_trials: 70
    n_startup_trials: 7
    request_list:
      - 'optimizer.params.weight_decay': 1.e-08
        'optimizer.params.lr': 1.e-3

        'data.loaders.unsupervised_train.batch_size': 8 

        'model.encoder.params.num_layers': 1
        'model.encoder.params.hidden_size': 512

        'model.preprocess.params.time_process': 'cat'
        'model.preprocess.params.num_norm': False
        'model.preprocess.params.cat_emb_dim': 64
        'model.preprocess.params.num_emb_dim': 64

        'model.aggregation.name': "TakeLastHidden"
    target_metric: ${tasks}
  suggestions:
    optimizer.params.weight_decay: [suggest_float, {low: 1.e-10, high: 1.e-2, log: True}]
    optimizer.params.lr: [suggest_float, {low: 1.e-5, high: 1.e-2, log: True}]

    data.loaders.unsupervised_train.batch_size: [suggest_categorical, {choices: [4, 8, 16]}] #[64, 128, 256, 512]

    model.encoder.params.num_layers: [suggest_int, {low: 1, high: 5, log: False}]
    model.encoder.params.hidden_size: [suggest_int, {low: 64, high: 1024, log: True}]

    model.preprocess.params.num_norm: [suggest_categorical, {choices: [true, false]}]
    model.preprocess.params.cat_emb_dim: [suggest_int, {low: 1, high: 128, log: False}]
    model.preprocess.params.num_emb_dim: [suggest_int, {low: 1, high: 128, log: False}]

    model.aggregation.name: [suggest_categorical, {choices: ["TakeLastHidden", "ValidHiddenMean"]}]
