optimizer:
  params:
    weight_decay: 0.00632829396323638
    lr: 5.503208995756976e-05
unsupervised_loss:
  params:
    temperature: 0.01133748127401839
data:
  loaders:
    unsupervised_train:
      batch_size: 64
model:
  encoder:
    params:
      num_layers: 2
      hidden_size: 726
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 124
      num_emb_dim: 124
  aggregation:
    name: TakeLastHidden
