optimizer:
  params:
    weight_decay: 4.422988091591908e-07
    lr: 0.0023607904573148854
unsupervised_loss:
  params:
    temperature: 0.061482406543551596
data:
  loaders:
    unsupervised_train:
      batch_size: 512
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 899
  preprocess:
    params:
      time_process: cat
      num_norm: true
      cat_emb_dim: 95
      num_emb_dim: 55
  aggregation:
    name: TakeLastHidden
