optimizer:
  params:
    weight_decay: 0.00011103810095992147
    lr: 2.14227158452242e-05
model:
  params:
    hidden_size: 352
    num_heads: 8
    query_aggregation: mean
    dropout: 0.05
    num_blocks: 2
    num_passes_over_block: 2
    cat_emb_dim: 96
    num_emb_dim: 64
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.6285638632552495
        span_len: 98
        span_share: 0.55
        random_token_prob: 0.05
        keep_event_prob: 0.1
        partial_cat_feature_prob: 0.2
        partial_num_feature_prob: 0.0
