optimizer:
  params:
    weight_decay: 5.595807965868975e-07
    lr: 2.042193293853403e-05
model:
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 8
      num_emb_dim: 72
      enc_hidden_size: 512
      emb_size: 1024
      enc_num_layers: 4
      n_head: 4
  aggregation:
    name: ValidHiddenMean
