optimizer:
  params:
    weight_decay: 9.694051785481518e-07
    lr: 1.6293209672945552e-05
model:
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 104
      num_emb_dim: 56
      enc_hidden_size: 1007
      emb_size: 1024
      enc_num_layers: 1
  aggregation:
    name: TakeLastHidden
