optimizer:
  params:
    weight_decay: 2.191523642596207e-06
    lr: 0.00018642797247853192
model:
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 96
      num_emb_dim: 40
      enc_hidden_size: 256
      emb_size: 256
      enc_num_layers: 4
      n_head: 2
  aggregation:
    name: TakeLastHidden
