optimizer:
  params:
    weight_decay: 6.319249744234459e-05
    lr: 0.0006709305170140477
model:
  params:
    hidden_size: 448
    num_heads: 2
    dropout: 0.15000000000000002
    num_blocks: 1
    num_passes_over_block: 2
    cat_emb_dim: 112
    num_emb_dim: 192
    masker:
      params:
        mask_prob: 0.2855582119300288
        span_len: 89
        span_share: 0.15000000000000002
        random_token_prob: 0.05
        keep_event_prob: 0.05
        partial_cat_feature_prob: 0.5
        partial_num_feature_prob: 0.1
