optimizer:
  params:
    weight_decay: 5.403622944472389e-08
    lr: 0.000757288528684455
model:
  params:
    hidden_size: 320
    num_heads: 4
    dropout: 0.1
    num_blocks: 2
    num_passes_over_block: 2
    cat_emb_dim: 208
    num_emb_dim: 80
    masker:
      params:
        mask_prob: 0.25777652162626097
        span_len: 5
        span_share: 0.25
        random_token_prob: 0.0
        keep_event_prob: 0.15
        partial_cat_feature_prob: 0.0
        partial_num_feature_prob: 0.1
