optimizer:
  params:
    weight_decay: 1.0197644964452597e-08
    lr: 2.8215834491567153e-05
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 3
      hidden_size: 711
  preprocess:
    params:
      time_process: cat
      num_norm: false
      cat_emb_dim: 127
      num_emb_dim: 102
  aggregation:
    name: TakeLastHidden
