optimizer:
  params:
    weight_decay: 2.890536401174065e-05
    lr: 0.004972747644441923
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 3
      dropout: 0.00021742702888803348
  preprocess:
    params:
      time_process: diff
      num_norm: false
      cat_emb_dim: 65
      num_emb_dim: 126
  aggregation:
    name: TakeLastHidden
