optimizer:
  params:
    weight_decay: 2.6956916116700772e-08
    lr: 0.0010452207930206942
model:
  preprocess:
    params:
      num_norm: false
      cat_emb_dim: 48
      num_emb_dim: 8
      enc_hidden_size: 755
      emb_size: 1024
      enc_num_layers: 4
  aggregation:
    name: ValidHiddenMean
