log_dir: log/age
patience: 10
n_classes: 4
main_metric: MulticlassAccuracy
main_loss: 
  name: nn.CrossEntropyLoss
tasks:
- target__reg_amount__local__r2
- target__age__global__accuracy+f1_macro
- target__forecast__local__r2
- target__anomaly__global__roc_auc+f1_macro+accuracy

cc: 
  small_group: 202
ee:

nn:
  - amount_rur

data:
  dataset:
    parquet_path: "data/age/preprocessed/train"
    random_split: true
    split_seed: 42

    split_sizes: 
      - 0.85   # train
      - 0.15  # train_val

  preprocessing:
    common_pipeline: &common_pipeline
      max_seq_len: 1000
      time_name: trans_date
      index_name: client_id
      target_name: age
      cat_cardinalities: ${cc}
      num_names: ${nn}
      median_length: ${min:730, ${data.preprocessing.common_pipeline.max_seq_len}}
      batch_transforms:
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - TargetToLong
        - MaskValid
        - Logarithm:
            names: ["amount_rur"]
    gen_pipeline:
      <<: *common_pipeline
      max_seq_len: 1000000
    primenet_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - TargetToLong
        - MaskValid
        - Logarithm:
            names: ["amount_rur"]
        - PrimeNetSampler:
            segment_num: 3

  loaders:
    train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      drop_incomplete: true
      shuffle: true
      loop: false
      num_workers: 4
      random_seed: 42
    full_train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    train_val:
      split_idx: 1
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    gen_train:
      split_idx: 0
      preprocessing: gen_pipeline
      batch_size: 32
      num_workers: 4
    gen_train_val:
      split_idx: 1
      preprocessing: gen_pipeline
      batch_size: 32
      num_workers: 4


test_data:
  dataset:
    parquet_path: "data/age/preprocessed/test"
    split_sizes: 
      - 1.0
  preprocessing:
    common_pipeline: *common_pipeline
    gen_pipeline:
      <<: *common_pipeline
      max_seq_len: 1000000
  loaders:
    test:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    gen_test:
      split_idx: 0
      preprocessing: gen_pipeline
      batch_size: 32
      num_workers: 4

metrics:
  - name: ${main_metric}
    params: 
      num_classes: ${n_classes}