log_dir: log/alpha
patience: 3
n_classes: 2
main_metric: MulticlassAUROC
main_loss: 
  name: nn.CrossEntropyLoss
tasks:
- target__prod__global__accuracy+f1_macro
- target__anomaly__local__roc_auc+f1_macro+accuracy
- target__reg_amount__local__r2
- target__forecast__local__r2

cc: 
  currency: 12
  operation_kind: 8
  card_type: 174
  operation_type: 23
  operation_type_group: 5
  ecommerce_flag: 4
  payment_system: 8
  income_flag: 4
  mcc: 109
  country: 25
  city: 164
  mcc_category: 28
  day_of_week: 8
ee:  
nn:
  - hour
  - amnt
  - hour_diff

data:
  dataset:
    parquet_path: "data/alpha/preprocessed/train"
    random_split: true
    split_seed: 42

    split_sizes: 
      - 0.85   # train
      - 0.15  # train_val

  preprocessing:
    common_pipeline: &common_pipeline
      max_seq_len: 512
      time_name: time_from_first_trn
      index_name: app_id
      target_name: shard
      num_names: ${nn}
      cat_cardinalities: ${cc}
      batch_transforms:
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - MaskValid
    contrastive_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - MaskValid
        - ContrastiveTarget
        - RandomSlices:
            split_count: 5
            cnt_min: 25
            cnt_max: 150
            short_seq_crop_rate: 0.8
            seed: 0
    primenet_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - MaskValid
        - PrimeNetSampler:
            segment_num: 3

  loaders:
    train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      drop_incomplete: true
      shuffle: true
      loop: false
      num_workers: 4
      random_seed: 42
    full_train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    train_val:
      split_idx: 1
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    hpo_val:
      split_idx: 2
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4

test_data:
  dataset:
    parquet_path: "data/alpha/preprocessed/test"
    split_sizes: 
      - 1.0
  preprocessing:
    common_pipeline: *common_pipeline
  loaders:
    test:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4

metrics:
  - name: ${main_metric}
    params: 
      num_classes: ${n_classes}
