log_dir: log/x5
patience: 5
n_classes: 6
main_metric: MulticlassAccuracy
main_loss:
  name: nn.CrossEntropyLoss
tasks:
- target__clf__global__accuracy+f1_macro
- target__anomaly__local__roc_auc
- target__reg__local__r2
- target__forecast__local__r2

cc:
  is_own_trademark: 3
  is_alcohol: 3
  level_1: 4
  level_2: 43
  level_3: 202
  level_4: 789
  segment_id: 118
nn:
  - trn_sum_from_iss
  - netto
  - regular_points_received
  - express_points_received
  - product_quantity
  - trn_sum_from_red # alot of missing, copyes iss
  - regular_points_spent
  - express_points_spent
  - purchase_sum
ee:
data:
  dataset:
    parquet_path: "data/x5-retail/preprocessed/train"
    random_split: true
    split_seed: 42
    split_sizes: 
      - 0.85   # train
      - 0.15  # train_val

  preprocessing:
    common_pipeline: &common_pipeline
      max_seq_len: 512
      time_name: transaction_datetime
      index_name: client_id
      target_name: _seq_len
      cat_cardinalities: ${cc}
      num_names: ${nn}
      batch_transforms:
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - MaskValid
        - FillNans:
            fill_value: 0
    gen_pipeline:
      <<: *common_pipeline
      max_seq_len: 1000000
    contrastive_pipeline:
      <<: *common_pipeline
      batch_transforms:
        - TimeToFeatures:
            process_type: ${model.preprocess.params.time_process}
        - FillNans:
            fill_value: 0
        - ContrastiveTarget
        - RandomSlices:
            split_count: 5
            cnt_min: 30
            cnt_max: 180
            short_seq_crop_rate: 0.8
            seed: 0

  loaders:
    train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      drop_incomplete: true
      shuffle: true
      loop: false
      num_workers: 4
      random_seed: 42
    full_train:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    train_val:
      split_idx: 1
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    gen_train:
      split_idx: 0
      preprocessing: gen_pipeline
      batch_size: 32
      num_workers: 4
    gen_train_val:
      split_idx: 1
      preprocessing: gen_pipeline
      batch_size: 32
      num_workers: 4

test_data:
  dataset:
    parquet_path: "data/x5-retail/preprocessed/test"
    split_sizes: 
      - 1.0
  preprocessing:
    common_pipeline: *common_pipeline
    gen_pipeline:
      <<: *common_pipeline
      max_seq_len: 1000000
  loaders:
    test:
      split_idx: 0
      preprocessing: common_pipeline
      batch_size: 128
      num_workers: 4
    gen_test:
      split_idx: 0
      preprocessing: gen_pipeline
      batch_size: 32
      num_workers: 4

metrics:
  - name: ${main_metric}
    params: 
      num_classes: ${n_classes}