optimizer:
  params:
    weight_decay: 3.3783091835411787e-10
    lr: 3.752419840356616e-05
model:
  preprocess:
    params:
      num_norm: true
      cat_emb_dim: 128
      num_emb_dim: 88
      enc_hidden_size: 706
      emb_size: 1024
      enc_num_layers: 1
  aggregation:
    name: TakeLastHidden
