optimizer:
  params:
    weight_decay: 1.4303270081812846e-05
    lr: 0.0001381744310626628
model:
  encoder:
    params:
      num_layers: 3
      dropout: 0.015207866009611692
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 118
      num_emb_dim: 43
  aggregation:
    name: ValidHiddenMean
unsupervised_loss:
  params:
    margin: 0.24195278138817267
