optimizer:
  params:
    weight_decay: 1.5424835793906847e-07
    lr: 0.0017136418477904478
unsupervised_loss:
  params:
    temperature: 0.06387691151978935
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 1
      hidden_size: 880
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 26
      num_emb_dim: 114
  aggregation:
    name: ValidHiddenMean
