optimizer:
  params:
    weight_decay: 2.818582194456375e-08
    lr: 3.9889892091044716e-05
model:
  params:
    hidden_size: 128
    objective_projection_mode: online_target
    ema_tau: 0.999
    downstream_embedding_source: online
    context_position_mode: encoder
    predictor_hidden_multiplier: 2.0
    num_heads: 8
    query_aggregation: mean
    dropout: 0.2
    num_blocks: 4
    num_passes_over_block: 2
    cat_emb_dim: 32
    num_emb_dim: 112
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.7928940515888274
