optimizer:
  params:
    weight_decay: 8.389216003705662e-10
    lr: 2.5583366257559534e-05
model:
  params:
    hidden_size: 512
    objective_projection_mode: online_target
    ema_tau: 0.999
    downstream_embedding_source: target
    context_position_mode: predictor
    predictor_hidden_multiplier: 2.0
    num_heads: 8
    query_aggregation: last
    dropout: 0.1
    num_blocks: 1
    num_passes_over_block: 2
    cat_emb_dim: 112
    num_emb_dim: 112
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.2579060639373557
