optimizer:
  params:
    weight_decay: 1.225956588674961e-10
    lr: 0.00015014492136647094
model:
  params:
    hidden_size: 256
    objective_projection_mode: online_target
    ema_tau: 0.9999
    downstream_embedding_source: online
    context_position_mode: predictor
    predictor_hidden_multiplier: 2.0
    num_heads: 4
    query_aggregation: last
    dropout: 0.0
    num_blocks: 4
    num_passes_over_block: 1
    cat_emb_dim: 96
    num_emb_dim: 32
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.68509206956718
