optimizer:
  params:
    weight_decay: 0.0003370317825488149
    lr: 0.0018136243748996528
model:
  params:
    hidden_size: 576
    num_heads: 8
    query_aggregation: last
    dropout: 0.0
    num_blocks: 3
    num_passes_over_block: 2
    cat_emb_dim: 80
    num_emb_dim: 32
    embedding_size: 1024
    masker:
      params:
        mask_prob: 0.4701682239600034
        span_len: 15
        span_share: 0.75
        random_token_prob: 0.05
        keep_event_prob: 0.15
        partial_cat_feature_prob: 0.30000000000000004
        partial_num_feature_prob: 0.35000000000000003
