optimizer:
  params:
    weight_decay: 3.8477368479565235e-09
    lr: 0.0025381688673536498
unsupervised_loss:
  params:
    temperature: 0.02745969074283837
data:
  loaders:
    unsupervised_train:
      batch_size: 128
model:
  encoder:
    params:
      num_layers: 2
      hidden_size: 315
  preprocess:
    params:
      time_process: diff
      num_norm: true
      cat_emb_dim: 13
      num_emb_dim: 97
  aggregation:
    name: TakeLastHidden
